apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: 7111418/tawazun:latest
          name: webserver
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: mysql
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: tawazun
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: DevOps2022
